### ISSUE TITLE
Size prop has no effect

### ISSUE THREAD

**Issue by amaury-tobias** [Kholid060/vue-mdijs#10]
I can't use `size` prop to scale icons i test some options and replace `view-box` with `viewBox` worked
https://github.com/Kholid060/vue-mdijs/blob/7578a82f2e4e142fa24def5e71f2c3fd8a52f41b/src/components/vue-mdijs.vue#L3

**Comment by Kholid060** [comment]
Hi, I have fixed this on latest version.
